### ISSUE TITLE
GUI freezes when I try to navigate to new window

### ISSUE THREAD

**Issue by briananmayes** [TechnologyClassroom/SignIn#1]
In my classes.py file, I've created 3 classes, 1 for uploading .csv files, signing in and registering new users. Once I navigate to the second window "Sign In," the GUI freezes when I click anywhere on the window. While doing research, I have read that it might be necessary to add a callback or a thread. 

I also found a tutorial for creating multiple windows in tkinter, but when I try to implement that code into my existing code, the window does not display at all. 

Example code for creating multiple windows taken from: pythonprogramming.net
[windows.txt](https://github.com/TechnologyClassroom/SignIn/files/634913/windows.txt)

**Comment by TechnologyClassroom** [comment]
The windows.txt file works for me.

I am testing on a Debian 8 vm with Python 3.4.2 and python3-tk.  I get this error when clicking skip:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1536, in __call__
    return self.func(*args)
  File "classes.py", line 52, in new_window1
    myGUI = SecondWindow(root2)
  File "classes.py", line 72, in __init__
    self.build_window()
  File "classes.py", line 96, in build_window
    yscroll.grid(row=3)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 2060, in grid_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager grid inside . which already has slaves managed by pack
```

**Comment by TechnologyClassroom** [comment]
tk was confused between pack and grid.

I did a simple fix of replacing 'pack' with 'grid' and it does not have fatal crashes.
