### ISSUE TITLE
signin.py ends with Abort Trap 6

### ISSUE THREAD

**Issue by thejonpearson** [TechnologyClassroom/SignIn#3]
~$ python signin.py
Abort trap: 6

~$ python -V
Python 2.7.10

If I comment out the Python3 tkinter import code (3 lines, from except ImportError and two after), I hit a syntax error later (line 28, separate issue) 

Some quick searches suggest there may be an issue with versions of tkinter on OSX Sierra.

**Comment by thejonpearson** [comment]
Normally I'd call this an environment error rather than code, but as the stated goal is simple and for non-profit use, I hesitate to suggest environment changes be made when there's a good chance the likely end users will be pretty non-technical.   I'll try setting up some blank environments to find what triggers it exactly, and maybe there's a way around it that doesn't involve pulling installed libraries from non-default sources.

**Comment by TechnologyClassroom** [comment]
I just tested it with Ubuntu and it loads.

```
user@ubuntu:~/builds/SignIn$ python2 signin.py
user@ubuntu:~/builds/SignIn$ python2 -V
Python 2.7.12
```

I am not as familiar with Sierra and the Apple universe anymore, but it seems like it is broken according to the Python docs.

"If you are using Mac OS X 10.7 or later, the Apple-supplied Tcl/Tk 8.5 still has serious bugs that can cause application crashes. If you wish to use IDLE or Tkinter, install and use a newer version of Python and of Tcl/Tk."
From https://www.python.org/download/mac/tcltk/

**Comment by TechnologyClassroom** [comment]
@thejonpearson, can you try installing the latest python 2 and Tkinter and report back?  I could load up a Mac VM, but it may take a while for me to update to Sierra.

**Comment by TechnologyClassroom** [comment]
I have updated the README.md to reflect the broken library.
